// Code generated by MockGen. DO NOT EDIT.
// Source: ./model/interface.go

// Package model is a generated GoMock package.
package model

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/jiebutech/uc/types"
)

// MockUserEntity is a mock of UserEntity interface.
type MockUserEntity struct {
	ctrl     *gomock.Controller
	recorder *MockUserEntityMockRecorder
}

// MockUserEntityMockRecorder is the mock recorder for MockUserEntity.
type MockUserEntityMockRecorder struct {
	mock *MockUserEntity
}

// NewMockUserEntity creates a new mock instance.
func NewMockUserEntity(ctrl *gomock.Controller) *MockUserEntity {
	mock := &MockUserEntity{ctrl: ctrl}
	mock.recorder = &MockUserEntityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserEntity) EXPECT() *MockUserEntityMockRecorder {
	return m.recorder
}

// GetAvatar mocks base method.
func (m *MockUserEntity) GetAvatar() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatar")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAvatar indicates an expected call of GetAvatar.
func (mr *MockUserEntityMockRecorder) GetAvatar() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatar", reflect.TypeOf((*MockUserEntity)(nil).GetAvatar))
}

// GetID mocks base method.
func (m *MockUserEntity) GetID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockUserEntityMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockUserEntity)(nil).GetID))
}

// GetIdentify mocks base method.
func (m *MockUserEntity) GetIdentify() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentify")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIdentify indicates an expected call of GetIdentify.
func (mr *MockUserEntityMockRecorder) GetIdentify() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentify", reflect.TypeOf((*MockUserEntity)(nil).GetIdentify))
}

// GetLoginType mocks base method.
func (m *MockUserEntity) GetLoginType() types.LoginType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginType")
	ret0, _ := ret[0].(types.LoginType)
	return ret0
}

// GetLoginType indicates an expected call of GetLoginType.
func (mr *MockUserEntityMockRecorder) GetLoginType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginType", reflect.TypeOf((*MockUserEntity)(nil).GetLoginType))
}

// GetNickname mocks base method.
func (m *MockUserEntity) GetNickname() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNickname")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNickname indicates an expected call of GetNickname.
func (mr *MockUserEntityMockRecorder) GetNickname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNickname", reflect.TypeOf((*MockUserEntity)(nil).GetNickname))
}

// GetPassword mocks base method.
func (m *MockUserEntity) GetPassword() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassword")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPassword indicates an expected call of GetPassword.
func (mr *MockUserEntityMockRecorder) GetPassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassword", reflect.TypeOf((*MockUserEntity)(nil).GetPassword))
}

// GetUserName mocks base method.
func (m *MockUserEntity) GetUserName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserName indicates an expected call of GetUserName.
func (mr *MockUserEntityMockRecorder) GetUserName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserName", reflect.TypeOf((*MockUserEntity)(nil).GetUserName))
}

// IdKey mocks base method.
func (m *MockUserEntity) IdKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// IdKey indicates an expected call of IdKey.
func (mr *MockUserEntityMockRecorder) IdKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdKey", reflect.TypeOf((*MockUserEntity)(nil).IdKey))
}

// IdentifyKey mocks base method.
func (m *MockUserEntity) IdentifyKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentifyKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// IdentifyKey indicates an expected call of IdentifyKey.
func (mr *MockUserEntityMockRecorder) IdentifyKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentifyKey", reflect.TypeOf((*MockUserEntity)(nil).IdentifyKey))
}

// LoginTypeKey mocks base method.
func (m *MockUserEntity) LoginTypeKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginTypeKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// LoginTypeKey indicates an expected call of LoginTypeKey.
func (mr *MockUserEntityMockRecorder) LoginTypeKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginTypeKey", reflect.TypeOf((*MockUserEntity)(nil).LoginTypeKey))
}

// PasswordKey mocks base method.
func (m *MockUserEntity) PasswordKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// PasswordKey indicates an expected call of PasswordKey.
func (mr *MockUserEntityMockRecorder) PasswordKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordKey", reflect.TypeOf((*MockUserEntity)(nil).PasswordKey))
}

// SetId mocks base method.
func (m *MockUserEntity) SetId(id int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetId", id)
}

// SetId indicates an expected call of SetId.
func (mr *MockUserEntityMockRecorder) SetId(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetId", reflect.TypeOf((*MockUserEntity)(nil).SetId), id)
}

// SetIdentify mocks base method.
func (m *MockUserEntity) SetIdentify(identify string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIdentify", identify)
}

// SetIdentify indicates an expected call of SetIdentify.
func (mr *MockUserEntityMockRecorder) SetIdentify(identify interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIdentify", reflect.TypeOf((*MockUserEntity)(nil).SetIdentify), identify)
}

// SetLoginType mocks base method.
func (m *MockUserEntity) SetLoginType(loginType types.LoginType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLoginType", loginType)
}

// SetLoginType indicates an expected call of SetLoginType.
func (mr *MockUserEntityMockRecorder) SetLoginType(loginType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLoginType", reflect.TypeOf((*MockUserEntity)(nil).SetLoginType), loginType)
}

// SetUsername mocks base method.
func (m *MockUserEntity) SetUsername(username string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUsername", username)
}

// SetUsername indicates an expected call of SetUsername.
func (mr *MockUserEntityMockRecorder) SetUsername(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUsername", reflect.TypeOf((*MockUserEntity)(nil).SetUsername), username)
}

// TableName mocks base method.
func (m *MockUserEntity) TableName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableName")
	ret0, _ := ret[0].(string)
	return ret0
}

// TableName indicates an expected call of TableName.
func (mr *MockUserEntityMockRecorder) TableName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableName", reflect.TypeOf((*MockUserEntity)(nil).TableName))
}

// ToMap mocks base method.
func (m *MockUserEntity) ToMap() map[string]interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToMap")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// ToMap indicates an expected call of ToMap.
func (mr *MockUserEntityMockRecorder) ToMap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToMap", reflect.TypeOf((*MockUserEntity)(nil).ToMap))
}

// UsernameKey mocks base method.
func (m *MockUserEntity) UsernameKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsernameKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// UsernameKey indicates an expected call of UsernameKey.
func (mr *MockUserEntityMockRecorder) UsernameKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsernameKey", reflect.TypeOf((*MockUserEntity)(nil).UsernameKey))
}

// MockUserResource is a mock of UserResource interface.
type MockUserResource struct {
	ctrl     *gomock.Controller
	recorder *MockUserResourceMockRecorder
}

// MockUserResourceMockRecorder is the mock recorder for MockUserResource.
type MockUserResourceMockRecorder struct {
	mock *MockUserResource
}

// NewMockUserResource creates a new mock instance.
func NewMockUserResource(ctrl *gomock.Controller) *MockUserResource {
	mock := &MockUserResource{ctrl: ctrl}
	mock.recorder = &MockUserResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserResource) EXPECT() *MockUserResourceMockRecorder {
	return m.recorder
}

// GenUser mocks base method.
func (m *MockUserResource) GenUser() UserEntity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenUser")
	ret0, _ := ret[0].(UserEntity)
	return ret0
}

// GenUser indicates an expected call of GenUser.
func (mr *MockUserResourceMockRecorder) GenUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenUser", reflect.TypeOf((*MockUserResource)(nil).GenUser))
}

// GetUserByIdentify mocks base method.
func (m *MockUserResource) GetUserByIdentify(dest UserEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByIdentify", dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetUserByIdentify indicates an expected call of GetUserByIdentify.
func (mr *MockUserResourceMockRecorder) GetUserByIdentify(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByIdentify", reflect.TypeOf((*MockUserResource)(nil).GetUserByIdentify), dest)
}

// GetUserByUsername mocks base method.
func (m *MockUserResource) GetUserByUsername(dest UserEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserResourceMockRecorder) GetUserByUsername(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserResource)(nil).GetUserByUsername), dest)
}

// UpdatePassword mocks base method.
func (m *MockUserResource) UpdatePassword(dest UserEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserResourceMockRecorder) UpdatePassword(dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserResource)(nil).UpdatePassword), dest)
}
